import json

first = ['Fuyuko', 'Mimi', 'Yoriko', 'Misato', 'Mikasa', 'Satoko', 'Kaneko', 'Haruka', 'Kinuye', 'Seiko', 'Itsuko', 'Hiroe', 'Kinuko', 'Ichi', 'Kumiko', 'Fusae', 'Maeko', 'Shioko', 'Ume', 'Maru', 'Machiko', 'Hoshiyo', 'Hikaru', 'Toyoko', 'Saito', 'Makiko', 'Umeka', 'Reiko', 'Tamiyo', 'Otsune', 'Komachi', 'Kiyomi', 'Yui', 'Oki', 'Mizuki', 'Rui', 'Rieko', 'Yoshiko', 'Mari', 'Inoue', 'Mineko', 'Nao', 'Juri', 'Yumena', 'Seka', 'Masae', 'Nariko', 'Minami', 'Nomi', 'Mutsuko', 'Mami', 'Sayuri', 'Hiromi', 'Kishi', 'Tomoko', 'Noriko', 'Shizuka', 'Matsu', 'Namiko', 'Kiyoko', 'Aki', 'Nanako', 'Yaeko', 'Rinako', 'Remi', 'Mako', 'Nanaka', 'Sora', 'Emiko', 'Rika', 'Kazumi', 'Sama', 'Sakiko', 'Tokiko', 'Maya', 'Midori', 'Saeko', 'Tamaki', 'Tsuki', 'Hatsuyo', 'Ruriko', 'Ikuko', 'Chikako', 'Hisako', 'Otsu', 'Ayako', 'Sakura', 'Masako', 'Hanako', 'Yoko', 'Umeko', 'Megumi', 'Ise', 'Hoshie', 'Sakea', 'Kaoru', 'Ginko', 'Misa', 
'Joruri', 'Kin', 'Ami', 'Fumiki', 'Fumiko', 'Jun', 'Mayumi', 'Kadiri', 'Kisa', 'Namie', 'Maemi', 'Mai', 'Katsumi', 'Sui', 'Kayoko', 'Koiso', 'Toshie', 'Saeki', 'Fujiko', 'Akari', 'Natsumi', 'Yumi', 'Saya', 'Rumiko', 'Hiroko', 'Akira', 'Euiko', 'Raicho', 'Ritsuko', 'Naho', 'Gemmei', 'Yu', 'Yasu', 'Mayoko', 'Yukiyo', 'Yuko', 'Iku', 'Mitsu', 'Miiko', 'Honami', 'Minako', 'Etsuko', 'Omitsu', 'Chiyo', 'Ochiyo', 'Nyoko', 'Asuka', 'Mieko', 'Mayu', 'Chitose', 'Hitomi', 'Kimie', 'Kochiyo', 'Sumie', 'Tansho', 'Eri', 'Hiroshi', 'Oharu', 'Yayoi', 'Michi', 'Yukako', 'Ayame', 'Man', 'Fumi', 'Rin', 'Tsubasa', 'Sakue', 'Katsue', 'Isako', 'Eiko', 'Sakamae', 'Kiko', 'Ryo', 'Miwako', 'Norie', 'Tsuya', 'Rie', 'Tara', 'Kit', 'Teruyo', 'Masumi', 'Saki', 'Yuri', 'Kazue', 'Michiko', 'Akuro', 'Suko', 'Yuka', 'Hisae', 'Aoi', 'Miyo', 'Yumiko', 'Tomi', 'Kunie', 'Tadako', 'Miya', 'Yukari', 'Aono', 'Yuya', 'Takako', 'Miliko', 'Harukichi', 'Shinobu', 'Yoshi', 'Chie', 'Yori', 'Miyoshi', 'Kahori', 'Kuniko', 'Mana', 'Yumako', 'Nozomi', 'Wazuka', 'Kioko', 'Keiko', 'Mae', 'Kameko', 'Hanae', 'Hama', 'Haruko', 'Eriko', 'Shoko', 'Hitomo', 'Nene', 'Sen', 'Sae', 'Hoshi', 'Aya', 'Tomomi', 'Kasuga', 'Kyoko', 'Nayoko', 'Sadako', 'Sumi', 'Sei', 'Sachi', 'Momoko', 'Fumiyo', 'Yuriko', 'Rikako', 'Yodo', 'Tamami', 'Maiko', 'Mina', 'Haniko', 'Tamiko', 'Yoshike', 'Mayuko', 'Asako', 'Kazuko', 'Alice', 'Katsuko', 'Ayano', 'Nori', 'Junko', 'Tama', 'Naomi', 'Risa', 'Risako', 'Mariko', 'Kimiko', 'Satomi', 'Namika', 'Tae', 'Ryoko', 'Sakuko', 'Sayoko', 'Mino', 'Miho', 'Sachiko', 'Setsuko', 'Naoko', 'Koi', 'Yutsuko', 'Kaori', 'Akemi', 'Mihoko', 'Nahoko', 'Ikue', 'Saori', 'Maki', 'Aiko', 'Emi', 'Riku', 'Tsuyu', 'Tai', 'Miyako', 'Ruri', 'Ryu', 'Tokiyo', 'Izumi', 'Hinako', 'Rinoko', 'Nari', 'Machi', 'Chisato', 'Mamiko', 'Hana', 'Marika', 'Sawako', 'Chieko', 'Shizue', 'Natsuko', 'Kita', 'Atsuko', 'Okiku', 'Hitoshi', 'Ayaka', 'Shiori', 'Suzuko', 'Nanami', 'Romi', 'Kiyo', 'Miki', 'Kana', 'Hideko', 'Toshiko', 'Fumie', 'Yasuko', 'Tsukiyama', 'Hoshiko', 'Tokie', 'Koken', 'Sakuro', 'Mutsumi', 'Kimi', 'Yukiko', 'Raku', 'Yusuke', 'Kaede', 'Masami', 'Mayo', 'Nana', 'Hatsue', 'Chiyeko', 'Arisa', 'Sanako', 'Yuki', 'Naora', 'Chiaki', 'Kichi', 'Mitsuko', 'Toku', 'Urako', 'Madoka', 'Taniko', 'Utako', 'Tomiko', 'Kumi', 'Chika', 'Rina', 'Sakurako', 'Megu', 'Narumi', 'Mayako', 'Akiko', 'Mitsuyo', 'Akane', 'Ikuyo', 'Ai', 'Sayo', 'Manami', 'Okichi', 'Seki', 'Misako', 'Echiko', 'Mio', 'Kinuyo', 'Hisa', 'Harumi', 'Ema', 'Yae', 'Namiyo', 'Miyoko', 'Asami', 'Chikuma', 'Nami', 'Sata', 'Rei', 'Suzue', 'Tomoe', 'Shige', 'Sumiko', 'Shoken', 'Shizu']
last = ['Tsurimi', 'Karubo', 'Maeno', 'Ichiro', 'Odaka', 'Yasukawa', 'Sugase', 'Siagyo', 'Ichihara', 'Takeuchi', 'Kaneko', 'Ibi', 'Yoshihara', 'Tokaji', 'Utagawa', 'Koyama', 'Muraoka', 'Tsuda', 'Furusawa', 'Nataga', 'Komon', 'Kaminaga', 'Yanagi', 'Kahaya', 'Nakamura', 'Matsura', 'Shiotani', 'Hayashi', 'Mitsukuri', 'Kashiwagi', 'Takewaki', 'Ebisawa', 'Nagatsuka', 'Monomonoi', 'Kudara', 'Gakusha', 'Kajitani', 'Ariwara', 'Kawakami', 'Oyama', 'Ishida', 'Marugo', 'Joshuyo', 'Asanuma', 'Hirase', 'Kon', 'Arakida', 'Oishi', 'Shimazu', 'Toyoda', 'Tatsuko', 'Takaoka', 
'Tommii', 'Inouye', 'Santo', 'Nagasawa', 'Arita', 'Kunikida', 'Narita', 'Saji', 'Ki', 'Ooka', 'Yamanoue', 'Nakamoto', 'Tamazaki', 'Miyajima', 'Ishiyama', 'Yamaguchi', 'Ninomiya', 'Taku', 'Ibu', 'Kotara', 'Kawasawa', 'Sasada', 'Kondo', 'Shirasu', 'Sammiya', 'Tsutomu', 'Serizawa', 'Yoemon', 'Kanada', 'Kakinomoto', 'Segawa', 'Shoda', 'Hirasi', 'Terajima', 'Ouchi', 'Kishi', 'Saigo', 'Abukara', 'Noda', 'Imoo', 'Goto', 'Godo', 'Tadeshi', 'Iesada', 'Taketomo', 'Kamio', 'Fujimoto', 'Nogi', 'Okimasa', 'Akechi', 'Saga', 'Soseki', 'Hayashida', 'Shimazaki', 'Hojo', 'Sugita', 'Hira', 'Saeki', 'Someya', 'Harada', 'Kurogane', 'Hayata', 'Honda', 'Tanaka', 'Yamana', 'Shinko', 'Suzuki', 'Ina', 'Ushiba', 'Endoso', 'Yasujiro', 'Yamakawa', 'Kitao', 'Takara', 'Kasai', 'Ichisada', 'Sanda', 'Yoshizawa', 'Hiraki', 'Okura', 'Murata', 'Joshuya', 'Takarabe', 'Kataoka', 'Okanao', 'Kunomasu', 'Hachirobei', 'Ijichi', 'Tagawa', 'Sone', 'Ise', 'Otake', 'Watanabe', 'Matano', 'Takekawa', 'Hirota', 'Hatoyama', 'Shirai', 'Okanaya', 'Yunokawa', 'Enomoto', 'Etsuko', 'Taguchi', 'Yasui', 'Shibanuma', 'Fujikage', 'Hotta', 'Yoshizaki', 'Horri', 'Jumonji', 'Tansho', 'Hosokawa', 'Kumochi', 'Imagawa', 'Arato', 'Shionoya', 'Watoga', 'Sano', 'Koizumi', 'Tomioka', 'Konae', 'Komine', 'Koyanagi', 'Mazawa', 'Takagawa', 'Iwahashi', 
'Tsutaya', 'Yakuta', 'Shimedzu', 'Araki', 'Muro', 'Funabashi', 'Ozu', 'Abe', 'Hara', 'Tochikura', 'Jo', 'Ekoda', 'Yanagimoto', 'Oshima', 'Kimiyama', 'Horigoshi', 'Nishihara', 'Kimura', 'Noguchi', 'Isozaki', 'Ichigawa', 'Ogiwara', 'Satake', 'Matsushina', 'Eto', 'Mutsu', 'Mishima', 'Toshusai', 'Chiba', 'Tani', 'Horigome', 'Sato', 'Nakano', 'Sugimura', 'Taniguchi', 'Yuhara', 'Genda', 'Hayakawa', 'Okazaki', 'Eguchi', 'Ishikawa', 'Kakutama', 'Hattori', 'Nagata', 'Kasamatsu', 'Nakasone', 'Mihashi', 'Hashimoto', 'Mitsui', 'Tsumemasa', 'Sugisata', 'Izumi', 'Shidehara', 'Tomika', 'Nagumo', 'Tarumi', 'Hino', 'Suenami', 'Hideki', 'Irie', 'Miyazawa', 'Kenmotsu', 'Aida', 'Yamahata', 'Mushashibo', 'Katayanagi', 'Arakawa', 'Minamoto', 'Namiki', 'Kinoshita', 'Kazuyoshi', 'Toshishai', 'Katsura', 'Okimoto', 'Takabe', 'Yokokawa', 'Chikamatsu', 'Yamabe', 'Shimamura', 'Shiokawa', 'Nitta', 'Yamato', 'Kikugawa', 'Ando', 'Hoshino', 'Mori', 
'Miyoshi', 'Nishikawa', 'Ashia', 'Shunji', 'Kinashita', 'Kimio', 'Kijimuta', 'Shimizu', 'Tanizaki', 'Hamamoto', 'Nakasato', 'Nagai', 'Fukunaka', 'Makuda', 'Mitsuwa', 'Mizumaki', 'Nakanishi', 'Asari', 'Yamaha', 'Nakagawa', 'Omura', 'Yasuda', 'Uchiyama', 'Tsucgimoto', 'Tsuruga', 'Kawaii', 'Tsujimura', 'Nose', 'Mitzusaka', 'Shima', 'Daishi', 'Nishimuraya', 'Moto', 'Inukai', 'Nakahara', 'Hiroyuki', 'Jukodo', 'Higoshi', 'Morioka', 'Hida', 'Takagi', 'Oshin', 'Makioka', 'Ozaki', 'Tatenaka', 'Kagabu', 'Horiuchi', 'Ota', 'Yamanouchi', 'Miyagawa', 'Tomonaga', 'Mizoguchi', 'Numata', 'Shiratori', 'Mashita', 'Sarumara', 'Kumasaka', 'Tsukade', 'Atshushi', 'Kobayashi', 'Nakata', 'Modegi', 'Karube', 'Ishimura', 'Baba', 'Kuroki', 'Kase', 'Matokai', 'Hitomi', 'Shimaoka', 'Iseya', 'Hiraga', 'Shioya', 'Sasakawa', 'Kwakami', 'Matsuya', 'Sawamura', 'Sumitimo', 'Akatsuka', 'Seo', 'Kikuchi', 'Kawagichi', 'Fukusaku', 'Karamorita', 'Koruba', 
'Konishi', 'Sayuki', 'Hiraoka', 'Nagahama', 'Yamashita', 'Togo', 'Nagano', 'Katsu', 'Asahara', 'Masanobu', 'Ekiguchi', 'Matsukata', 'Kato', 'Ino', 'Tsushima', 'Tanuma', 'Nagisa', 'Hirayama', 'Satoya', 'Morita', 'Kanesaka', 'Takahama', 'Chino', 'Umeki', 'Matsuki', 'Marubeni', 'Ijiri', 'Yoshimatsu', 'Teshima', 'Ikoma', 'Wakatsuki', 'Takemitsu', 'Ohba', 'Kuramochi', 'Aota', 'Minatoya', 'Naito', 'Ozawa', 'Terada', 'Koguchi', 'Iwasa', 'Onoe', 'Kamata', 'Ogata', 'Yamada', 'Kiski', 'Ohmiya', 'Akaike', 'Hatakeda', 'Sugitani', 'Shigi', 'Matsuzawa', 'Yamhata', 'Higashikuni', 'Yano', 'Nozara', 'Mizutani', 'Senmatsu', 'Sakurai', 'Imamura', 'Mitsuharu', 'Mifune', 'Ogyu', 'Uoya', 'Okumura', 'Kawabata', 'Royama', 'Raikatuji', 'Kumagae', 'Kido', 'Asuhara', 'Hirokawa', 'Shibasawa', 'Watari', 'Ikina', 'Wakamatsu', 'Shige', 'Arishima', 'Gensai', 'Nakane', 'Yoshida', 'Otomo', 'Takagaki', 'Kentaro', 'Inoguchi', 'Takano', 'Yamanaka', 'Ueda', 'Makiguchi', 'Hatakeyama', 'Asai', 'Nakatsugawa', 'Miyamae', 'Shiba', 'Nonomura', 'Nishinosono', 'Idane', 'Akimoto', 'Obinata', 'Yoshimoto', 'Soga', 'Chishu', 'Kasaya', 'Sakamoto', 'Shiganori', 'Tanabe', 'Masuno', 'Yokoyama', 'Ii', 'Hayami', 'Fuse', 'Kawachi', 'Ui', 'Kawashima', 'Teshigahara', 'Komatsu', 'Tenshin', 'Okuma', 'Kagawa', 'Hisamatsu', 'Eda', 'Saionji', 'Mitsubishi', 'Katsushika', 'Erizawa', 'Sakubara', 'Funakoshi', 'Yanagawa', 'Itoh', 'Hanabusa', 'Kawaguchi', 'Maeda', 'Matsuo', 'Kikutake', 'Yamamura', 'Aihara', 'Ishinomori', 'Kuramoto', 
'Kusatsu', 'Ichiyusai', 'Torisei', 'Konoe', 'Nanami', 'Umari', 'Sakakibara', 'Kawamura', 'Hohki', 'Hirano', 'Tokuda', 'Takudome', 'Fukuyama', 'Adachi', 'Onishi', 'Tsukawaki', 'Kawai', 'Nobunaga', 'Kajahara', 'Kozu', 'Otani', 'Saitoh', 'Okui', 'Yanagita', 'Tokudome', 'Obuchi', 'Kuwabara', 'Hishida', 'Tsuruya', 'Aoki', 'Shimanouchi', 'Murkami', 'Kanagaki', 'Hasegawa', 'Nosaka', 'Iwakura', 'Egami', 'Ito', 'Kyubei', 'Kitamura', 'Tojo', 'Kunda', 'Kuno', 'Igarashi', 'Yonai', 'Haga', 'Kamon', 'Kamachi', 'Motoyoshi', 'Katayama', 'Kusunoki', 'Mazaki', 'Nakae', 
'Sakoda', 'Iriye', 'Murasaki', 'Fumihiko', 'Iemochi', 'Shirokawa', 'Miyake', 'Futabatei', 'Muruyama', 'Doi', 'Fugunaga', 'Yoshinobu', 'Takenouchi', 'Murayama', 'Nishimoto', 'Uetake', 'Bando', 'Iijima', 'Takashi', 'Morisue', 'Hamaguchi', 'Uno', 'Koga', 'Tayama', 'Kasahara', 'Nakajima', 'Fuschida', 'Ochida', 'Hamada', 'Wakai', 'Fujimaki', 'Kijmuta', 'Hamacho', 'Ieyoshi', 
'Okawa', 'Kanegawa', 'Tamura', 'Yamakazi', 'Nagahama', 'Okita', 'Sakiyurai', 'Shiraishi', 'Yamazaki', 'Uchida', 'Tsujimoto', 'Okakura', 'Higo', 'Shimohira', 'Kawamata', 'Endo', 'Natsume', 'Hiro', 'Sekigawa', 'Momotami', 'Maita', 'Ajibana', 'Tsumura', 'Takimoto', 'Matsumoto', 'Choshi', 'Otsu', 'Ebina', 'Matsumura', 'Komiya', 'Minami', 'Onohara', 'Nawabe', 'Tsunoda', 'Usami', 'Ariwa', 'Otsuka', 'Shiroyama', 'Sekine', 'Kita', 'Nakanoi', 'Miura', 'Yoshitomi', 'Koshin', 'Fukao', 'Shintaro', 'Numajiri', 'Satoh', 'Shikitei', 'Isoda', 'Amori', 'Kawagishi', 'Ishimaru', 'Takahashi', 'Matsuoka', 'Niijima', 'Fukushima', 'Okano', 'Mazuka', 'Ko', 'Masaoka', 'Fujiwara', 'Momotani', 'Sumida', 'Anami', 'Amaya', 'Higashiyama', 'Ichikawa', 'Takeshita', 'Toyota', 'Kitoaji', 'Akera', 'Yasutake', 'Tsukehara', 'Asahi', 'Nogushi', 'Fukuda', 'Toyama', 'Munkata', 'Kono', 'Okabe', 'Shirahata', 'Torii', 'Tsuchie', 'Yamawaki', 'Hiranuma', 'Noro', 'Uehara', 'Uboshita', 'Miyagi', 'Yuasa', 'Nakada', 'Shinozuka', 'Tomimoto', 'Sakai', 'Okamura', 'Yamaoka', 'Ogaki', 'Iseki', 'Ono', 'Tatsuno', 'Nijo', 'Jimbo', 'Kurkawa', 'Hatayama', 'Hiyama', 'Hama', 'Kokan', 'Okuda', 'Shigeki', 'Terakado', 'Sakuraba', 'Tokuoka', 'Takashita', 'Iwahara', 'Yamagata', 'Shimada', 'Inihara', 'Ienari', 'Fuchida', 'Sugihara', 'Saromi', 'Takei', 'Ueshima', 'Nagase', 'Imaizumi', 'Hiratasuka', 'Moriguchi', 'Kawasaki', 'Tsukamoto', 'Hasimoto', 'Aoyama', 'Tomori', 'Jippensha', 'Onoda', 'Morishita', 'Hyobanshi', 'Saito', 'Inaba', 'Sugawara', 'Matsuda', 'Tsubouchi', 'Mayuzumi', 'Arai', 'Gushiken', 'Shiga', 'Motoori', 'Tange', 'Iida', 'Sunada', 'Nakatoni', 'Nakadan', 'Shibaguchi', 'Kasuse', 'Kamioka', 'Takishida', 'Tsukatani', 'Taka', 'Kaima', 'Mizuno', 'Temko', 'Itami', 'Ayabito', 'Miki', 'Ikeda', 'Yamagishi', 'Handa', 'Deguchi', 'Tono', 'Kunisada', 'Minobe', 'Kaibara', 'Amagawa', 'Nakadai', 'Sakata', 'Shimakage', 'Morimoto', 'Maruya', 'Honami', 'Miyahara', 'Genji', 'Nozaki', 'Takamura', 'Kuroda', 'Hideyoshi', 'Ashikaga', 'Ishihara', 'Toru', 'Ogura', 'Shimura', 'Muraguchi', 'Ishiguro', 'Higuchi', 'Terauchi', 'Shirane', 'Hishikawa', 'Fuwa', 'Shibasaki', 'Idaka', 'Uesugi', 'Morri', 'Masudu', 'Sada', 'Matsumara', 'Munakata', 'Yosano', 'Shinozaki', 'Oinuma', 'Inao', 
'Takeda', 'Sonoda', 'Kurata', 'Akutagawa', 'Hotate', 'Ibuka', 'Kobi', 'Itagaki', 'Sasaki', 'Konda', 'Okada', 'Aizawa', 'Komagata', 'Umehara', 'Tawaraya', 'Ichimonji', 'Nishiwaki', 'Sekozawa', 'Yoshikawa', 'Kogara', 'Shizuma', 'Shiskikura', 'Nakao', 'Kamo', 'Miyamoto', 'Kurohiko', 'Omori', 'Kaza', 'Akita', 'Hagiwara', 'Hokusai', 'Sen', 'Masuko', 'Sassa', 'Fujita', 'Sugiyama', 'Nishi', 'Ashida', 'Ihara', 'Koiso', 'Enoki', 'Tamuro', 'Ieyasu', 'Toyotomi', 'Takasugi', 'Suzambo', 'Isayama', 'Nemoto', 'Kenkyusha', 'Tsukioka', 'Ohka', 'Sugai', 'Marusa', 'Yoshioka', 'Kikkawa', 'Narato', 'Kajiwara', 'Isobe', 'Iwasaki', 'Hirose', 'Kodama', 'Shibata', 'Mitsuya', 'Soho', 'Hyata', 'Takemura', 'Nishio', 'Fukumitsu', 'Kusonoki', 'Hanari', 'Kikui', 'Kojima', 'Miyazaki', 'Yasuhiro', 'Kawate', 'Kawayama', 'Kihara', 'Oichi', 'Okubo', 'Okuma', 'Masuzoe', 'Makino', 'Fukuzawa', 'Saiki', 'Inokuma', 'Kiyomi', 'Tsuji', 'Bunya', 'Tsuchiya', 'Kate', 'Uemura', 'Maehata', 'Hori', 'Baisotei', 'Kawatake', 'Yamamoto', 'Takemago', 'Asano', 'Nishimura', 'Mimasuya', 'Shichirobei', 'Kawazu', 'Hike', 'Chikanatsu', 'Shobo', 'Kudo', 'Dazai', 'Tankoshitsu', 'Deushi', 'Tabuchi', 'Kinugasa', 'Haruguchi', 'Kamisaka', 'Sawamatsu', 'Hasekura', 'Ochiai', 'Yamura', 'Akamatsu', 'Ohmae', 'Kuga', 'Ishibashi', 'Hagino', 'Ryusaki', 'Date', 'Murakami', 'Sakanoue', 'Yamakage', 'Takasu', 'Arihyoshi', 'Kogo', 'Shikuk', 'Hideaki', 'Otaka', 'Sanjo', 'Nomura', 'Nakayama', 'Kada', 'Hirata', 'Kurofuji', 'Kawasie', 'Toyoshima', 'Ohira', 'Anzai', 'Katsumata', 'Fujishima', 'Masoni', 'Takudo', 'Sotomura', 'Sakagami', 'Takayama', 'Ohishi', 'Tsukahara', 'Kitano', 'Osagawa', 'Okazawaya', 'Tatsuya', 'Yoshifumi', 'Inoue', 'Takizawa', 'Narahashi', 'Sohda', 'Tsukada', 'Kajiyama', 'Minabuchi', 'Kano', 'Matsushita', 'Kiriyama', 'Shigemitsu', 'Muso', 'Ayugai', 'Funaki', 'Toshitala?', 'Shibukji', 'Kurosawa', 'Yamaguchiya', 'Iitaka', 'Hosokaya', 'Kijima', 'Katsukawa', 'Okasawa', 'Murase', 'Kitagawa', 'Kubota', 'Nakazawa', 'Taira', 'Ezakiya', 'Kotoku', 'Komatsuzaki', 'Matoke', 'Watabe', 'Dan', 'Nakasawa', 'Ukiyo', 'Maruyama']

class Waifu:
    def __init__(self, identifier: str, guild, bdd):
        try:
            wid = int(identifier)
        except:
            name = identifier
            wid = self.get_id(identifier)
            if wid < 0 or wid > 100000:
                raise Exception("ID_NOT_FOUND")
        else:
            name = self.get(wid)
            if name == -1:
                raise Exception("NAME_NOT_FOUND")
        self.name = name
        self.id = wid
        self.owned, self.owner = self.owned(str(guild), bdd)
    def get(self, n: int):
        if n >= 0 and n <= 100000:
            n1 = n%len(first)
            n2 = n//len(first)
            return first[n1]+" "+last[n2]
        raise Exception("ID_NOT_FOUND")
    def get_id(self, n: str):
        n = n.title().strip().split(" ")
        if len(n) == 2:
            try:
                i_first = first.index(n[0])
                i_last  = last.index(n[1])
            except:
                pass
            else:
                return i_first+i_last*len(first)

            try:
                i_first = first.index(n[1])
                i_last  = last.index(n[0])
            except:
                pass
            else:
                return i_first+i_last*len(first)
        raise Exception("NAME_NOT_FOUND")
    def owned(self, guild, bdd):
        if self.id in bdd[guild]['waifus']:
            for user in bdd[guild]['users']:
                if self.id in bdd[guild]['users'][user]['waifus']:
                    return True, int(user)
        else:
            return False, -1